---
- name: Check if data disk is already mounted
  shell: mount | grep /dev/sdc1
  register: disk_mounted
  failed_when: false
  changed_when: false

- name: Create filesystem on data disk
  filesystem:
    fstype: ext4
    dev: /dev/sdc
  when: disk_mounted.rc != 0

- name: Create mount point
  file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0755'

- name: Mount data disk
  mount:
    path: "{{ project_dir }}"
    src: /dev/sdc
    fstype: ext4
    state: mounted
  when: disk_mounted.rc != 0

- name: Add to fstab
  mount:
    path: "{{ project_dir }}"
    src: /dev/sdc
    fstype: ext4
    state: present
  when: disk_mounted.rc != 0
