---
project_dir: /opt/tailscale-hub
admin_user: adminuser
timezone: UTC
tailscale_auth_key: "{{ vault_tailscale_auth_key }}"
openai_api_key: "{{ vault_openai_api_key }}"
openai_api_base: "{{ vault_openai_api_base }}"
grafana_password: "{{ vault_grafana_password }}"
restic_password: "{{ vault_restic_password }}"
azure_storage_account: "{{ vault_azure_storage_account }}"
azure_storage_key: "{{ vault_azure_storage_key }}"

# Additional configuration
docker_compose_version: "2.20.0"
backup_retention_days: 30
